export const dva = {
  config: {
    onError(err) {
      err.preventDefault();
      console.error(err.message);
    },
    initialState: {
      products: [
        { name: 'dva', id: 1 },
        { name: 'antd', id: 2 },
        { name: 'antd3', id: 3 },
      ],
      colorTypeParent: [
        {name: '父级1', id: 1},
        {name: '父级2', id: 2},
        {name: '父级13', id: 13},
      ],
      colorTypeChild: [
        {name: '子级1', id: 11},
        {name: '子级2', id: 12},
        {name: '子级13', id: 113},
      ],
      productTypeParent: [
        {name: '父级1', id: 1},
        {name: '父级2', id: 2},
        {name: '父级13', id: 13},
      ],
      productTypeChild: [
        {name: '子级1', id: 11},
        {name: '子级2', id: 12},
        {name: '子级13', id: 113},
      ],
      colorTypeList: [
        {name: '子级1', id: 1, parentName: '父级1'},
        {name: '子级2', id: 2, parentName: '父级1'},
        {name: '子级13', id: 13, parentName: '父级1'},
      ],
      currentColorType: {name: '子级13', id: 13, parentName: '父级1', parentId: 2},
      colorList: [
        {
          name: 'currentColor',
          id: 13,
          uid: 13,
          typeId: 113,
          typeName: '分类1',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: true,
        },
        {
          name: 'currentColor2',
          id: 13,
          uid: 13,
          typeId: 113,
          typeName: '分类2',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: true,
        },
        {
          name: 'currentColor3',
          id: 13,
          uid: 13,
          typeId: 113,
          typeName: '分类3',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: false,
        },
      ],
      currentColor: {
        name: 'currentColor',
        id: 13,
        uid: 13,
        typeId: 113,
        img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
        rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
        hot: true,
      },
      productTypeList: [
        {name: '子级1', id: 1, parentName: '父级1'},
        {name: '子级2', id: 2, parentName: '父级1'},
        {name: '子级13', id: 13, parentName: '父级1'},
      ],
      currentProductType: {name: '子级13', id: 13, parentName: '父级1', parentId: 2},
      allColor: [
        {
          name: 'currentColor',
          id: 13,
          uid: 13,
          key: 13,
          typeId: 113,
          typeName: '分类1',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: true,
        },
        {
          name: 'currentColor2',
          id: 14,
          uid: 14,
          key: 14,
          typeId: 113,
          typeName: '分类2',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: true,
        },
        {
          name: 'currentColor3',
          id: 15,
          uid: 15,
          key: 15,
          typeId: 113,
          typeName: '分类3',
          img: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          rendering: 'https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png',
          hot: false,
        },
      ],
    },
  },
};
